### ISSUE TITLE
[Server thread/ERROR]: Could not pass event LeavesDecayEvent to OtherDrops_1.13 v3.2.6 

### ISSUE THREAD

**Issue by arturek1666** [CoolLord22/OtherDrops#35]
**Describe the bug**
A big error in console

**To Reproduce**
To reproduce I just try to mine blocks that I have added to a list

**Expected behavior**
Massive spam in console :(

**Console error**
```
[10:32:50] [Server thread/ERROR]: Could not pass event LeavesDecayEvent to OtherDrops_1.13 v3.2.6
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.13.1.jar:git-Paper-275]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.1.jar:git-Paper-275]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.1.jar:git-Paper-275]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.1.jar:git-Paper-275]
	at net.minecraft.server.v1_13_R2.BlockLeaves.b(BlockLeaves.java:27) ~[patched_1.13.1.jar:git-Paper-275]
	at net.minecraft.server.v1_13_R2.IBlockData.b(IBlockData.java:220) ~[patched_1.13.1.jar:git-Paper-275]
	at net.minecraft.server.v1_13_R2.WorldServer.n_(WorldServer.java:568) ~[patched_1.13.1.jar:git-Paper-275]
	at net.minecraft.server.v1_13_R2.WorldServer.doTick(WorldServer.java:318) ~[patched_1.13.1.jar:git-Paper-275]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1076) ~[patched_1.13.1.jar:git-Paper-275]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:434) ~[patched_1.13.1.jar:git-Paper-275]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:945) ~[patched_1.13.1.jar:git-Paper-275]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:843) ~[patched_1.13.1.jar:git-Paper-275]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_13_R2.CraftWorld cannot be cast to com.sk89q.worldedit.world.World
	at com.gmail.zariust.otherdrops.listener.OdBlockListener.checkWorldguardLeafDecayPermission(OdBlockListener.java:58) ~[?:?]
	at com.gmail.zariust.otherdrops.listener.OdBlockListener.onLeavesDecay(OdBlockListener.java:77) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor858.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.1.jar:git-Paper-275]
	... 12 more
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Java Version java 8
 - Server Version: paperspigot 1.13.1
 - Plugin Version 3.2.6

**Comment by CoolLord22** [comment]
This is, yet again, another issue with WorldGuard. It’s not working properly because they updated their API. I’ll try to find some documentation and have a fix out ASAP.

**Comment by CoolLord22** [comment]
Fixed by https://github.com/CoolLord22/OtherDrops1.13/commit/10e09d5be5cd6f1a0a29e0982c1de4f511fd8409
