### ISSUE TITLE
Could not pass event EntityDamageByBlockEvent to OtherDrops_1.13 v3.2.6

### ISSUE THREAD

**Issue by subarct1c** [CoolLord22/OtherDrops#44]
**Describe the bug**
Console is spammed with errors when WorldGuard and OtherDrops are running on server.

**To Reproduce**
1. Start server with OtherDrops & WorldGuard
2. Have mob damaged by block (In my case lava)
3. Console with spam the error below.

**Console Error**
[01:36:56 ERROR]: Could not pass event EntityDamageByBlockEvent to OtherDrops_1.13 v3.2.6
java.lang.NoSuchMethodError: com.sk89q.worldguard.internal.platform.WorldGuardPlatform.getWorldByName(Ljava/lang/String;)Lcom/sk89q/worldedit/world/World;
        at com.gmail.zariust.otherdrops.event.OccurredEvent.setRegions(OccurredEvent.java:808) ~[?:?]
        at com.gmail.zariust.otherdrops.event.OccurredEvent.<init>(OccurredEvent.java:219) ~[?:?]
        at com.gmail.zariust.otherdrops.listener.OdEntityListener.onEntityDamage(OdEntityListener.java:63) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor404.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-488]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-488]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-488]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-488]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callEvent(CraftEventFactory.java:103) ~[patched_1.13.2.jar:git-Paper-488]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:723) ~[patched_1.13.2.jar:git-Paper-488]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:848) ~[patched_1.13.2.jar:git-Paper-488]
        at net.minecraft.server.v1_13_R2.EntityLiving.damageEntity0(EntityLiving.java:1520) ~[patched_1.13.2.jar:git-Paper-488]
        at net.minecraft.server.v1_13_R2.EntityLiving.damageEntity(EntityLiving.java:985) ~[patched_1.13.2.jar:git-Paper-488]
        at net.minecraft.server.v1_13_R2.EntityMonster.damageEntity(EntityMonster.java:43) ~[patched_1.13.2.jar:git-Paper-488]
        at net.minecraft.server.v1_13_R2.EntityGuardian.damageEntity(SourceFile:354) ~[patched_1.13.2.jar:git-Paper-488]
        at net.minecraft.server.v1_13_R2.Entity.burnFromLava(Entity.java:544) ~[patched_1.13.2.jar:git-Paper-488]
        at net.minecraft.server.v1_13_R2.Entity.W(Entity.java:484) ~[patched_1.13.2.jar:git-Paper-488]
        at net.minecraft.server.v1_13_R2.EntityLiving.W(EntityLiving.java:218) ~[patched_1.13.2.jar:git-Paper-488]
        at net.minecraft.server.v1_13_R2.EntityInsentient.W(EntityInsentient.java:200) ~[patched_1.13.2.jar:git-Paper-488]
        at net.minecraft.server.v1_13_R2.Entity.tick(Entity.java:357) ~[patched_1.13.2.jar:git-Paper-488]
        at net.minecraft.server.v1_13_R2.EntityLiving.tick(EntityLiving.java:2102) ~[patched_1.13.2.jar:git-Paper-488]
        at net.minecraft.server.v1_13_R2.EntityInsentient.tick(EntityInsentient.java:260) ~[patched_1.13.2.jar:git-Paper-488]
        at net.minecraft.server.v1_13_R2.EntityMonster.tick(EntityMonster.java:27) ~[patched_1.13.2.jar:git-Paper-488]
        at net.minecraft.server.v1_13_R2.World.entityJoinedWorld(World.java:1554) ~[patched_1.13.2.jar:git-Paper-488]
        at net.minecraft.server.v1_13_R2.World.g(World.java:1521) ~[patched_1.13.2.jar:git-Paper-488]
        at net.minecraft.server.v1_13_R2.World.tickEntities(World.java:1328) ~[patched_1.13.2.jar:git-Paper-488]
        at net.minecraft.server.v1_13_R2.WorldServer.tickEntities(WorldServer.java:615) ~[patched_1.13.2.jar:git-Paper-488]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1104) ~[patched_1.13.2.jar:git-Paper-488]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-488]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-488]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-488]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

**Desktop (please complete the following information):**
 - OS: Linux
 - Java Version: 1.8.0_191
 - Server Version: Paper version git-Paper-488 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
 - Plugin Version: 1.13-3.2.6 (and WorldGuard 7.0-SNAPSHOT build 1780)

**Comment by subarct1c** [comment]
I've joined the discord and done what it said to get access but I still can't see any channels other than #welcome. Discord name is frig1d#0001

**Comment by CrystalElixir** [comment]
Please actually _read_ what is in #welcome and you'll be able to see the other channels.

**Comment by CrystalElixir** [comment]
Roles have been added. Once again, sorry about that. It's been a long morning 😅

**Comment by CoolLord22** [comment]
Reopening issue as it’s confirmed to be causing problems on latest beta branch. Removing duplicate as it’s different from #28.
