### ISSUE TITLE
WorldGuard integration throwing NoSuchMethodError

### ISSUE THREAD

**Issue by Kamilkime** [CoolLord22/OtherDrops#49]
**Describe the bug**
An error is beign thrown whenever someone breaks a block
```java
[22:55:03] [Server thread/ERROR]: Could not pass event BlockBreakEvent to OtherDrops_1.13 v3.2.6
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:309) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
	at net.minecraft.server.v1_13_R2.PlayerInteractManager.breakBlock(PlayerInteractManager.java:292) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
	at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:219) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1176) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
	at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:40) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
	at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:10) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_191]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NoSuchMethodError: com.sk89q.worldguard.protection.regions.ProtectedRegion.contains(Lcom/sk89q/worldedit/Vector;)Z
	at com.gmail.zariust.otherdrops.event.OccurredEvent.setRegions(OccurredEvent.java:812) ~[?:?]
	at com.gmail.zariust.otherdrops.event.OccurredEvent.<init>(OccurredEvent.java:134) ~[?:?]
	at com.gmail.zariust.otherdrops.listener.OdBlockListener.onBlockBreak(OdBlockListener.java:107) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor140.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
	... 17 more
```

**To Reproduce**
Install the newest version of WorldGuard from bukkit.org and try to break a block

**Expected behavior**
Just a WG integration working as intended

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: Linux, MC hosting
 - Java Version: 8
 - Server Version: 1.13.2
 - Plugin Version: 3.2.6

**Additional context**
-

**Comment by CoolLord22** [comment]
Hi there! This hasn’t already been reported (at least 6 times xD) and has already been resolved in 3.2.7. As 3.2.7 is a beta build still, it’s not ready for release yet. However, if you would like the build, feel free to grab it from our discord server where beta updates are posted! Thank you for using GitHub, let us know if you have any questions/issues.
