### ISSUE TITLE
Errors in the console

### ISSUE THREAD

**Issue by Scremonetu** [CoolLord22/OtherDrops#68]
- OS: Linux
 - Java Version: 8 build 212
 - Server Version: Spigot 1.14
 - Plugin Version: 3.2.7

```
[20:46:18] [Server thread/ERROR]: Error occurred while enabling OtherDrops v3.2.7 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.Bukkit.getServerId()Ljava/lang/String;
	at com.gmail.zariust.otherdrops.OtherDrops.exportServerDetails(OtherDrops.java:211) ~[?:?]
	at com.gmail.zariust.otherdrops.OtherDrops.exportEnumLists(OtherDrops.java:198) ~[?:?]
	at com.gmail.zariust.otherdrops.OtherDrops.onEnable(OtherDrops.java:94) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:416) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:458) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:372) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:440) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:758) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```
```
[21:53:10] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to OtherDrops v3.2.7
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:505) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at net.minecraft.server.v1_14_R1.PlayerList.a(PlayerList.java:172) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at net.minecraft.server.v1_14_R1.LoginListener.c(LoginListener.java:149) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at net.minecraft.server.v1_14_R1.LoginListener.tick(LoginListener.java:53) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at net.minecraft.server.v1_14_R1.NetworkManager.a(NetworkManager.java:230) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at net.minecraft.server.v1_14_R1.ServerConnection.c(ServerConnection.java:119) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1077) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:953) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:798) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/io/IOUtils
	at com.gmail.zariust.otherdrops.Updater.getLastUpdate(Updater.java:27) ~[?:?]
	at com.gmail.zariust.otherdrops.Updater.runPlayerUpdateCheck(Updater.java:78) ~[?:?]
	at com.gmail.zariust.otherdrops.listener.PlayerJoinUpdateChecker.onPlayerJoinUpdateCheck(PlayerJoinUpdateChecker.java:25) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	... 13 more
Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.IOUtils
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_212]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:135) ~[spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81) ~[spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
	at com.gmail.zariust.otherdrops.Updater.getLastUpdate(Updater.java:27) ~[?:?]
	at com.gmail.zariust.otherdrops.Updater.runPlayerUpdateCheck(Updater.java:78) ~[?:?]
	at com.gmail.zariust.otherdrops.listener.PlayerJoinUpdateChecker.onPlayerJoinUpdateCheck(PlayerJoinUpdateChecker.java:25) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	... 13 more
```

**Comment by CoolLord22** [comment]
This is an issue with the updater. In the meantime, you can ignore it by just turning off the update notifications in the config. I’ll do some checking. To see what was changed from 1.13 to 1.14 and get back to you :)

**Comment by Scremonetu** [comment]
OS: Linux
Java Version: 8 build 212
Server Version: Spigot 1.14.1
Plugin Version: 3.2.7 Last
```
[16:28:23] [Server thread/ERROR]: Could not pass event BlockBreakEvent to OtherDrops v3.2.7
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-f690957]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-f690957]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-f690957]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:505) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-f690957]
	at net.minecraft.server.v1_14_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:286) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-f690957]
	at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:219) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-f690957]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1199) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-f690957]
	at net.minecraft.server.v1_14_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-f690957]
	at net.minecraft.server.v1_14_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-f690957]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-f690957]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.1.jar:git-Spigot-8043ebc-f690957]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [spigot-1.14.1.jar:git-Spigot-8043ebc-f690957]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.1.jar:git-Spigot-8043ebc-f690957]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [spigot-1.14.1.jar:git-Spigot-8043ebc-f690957]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:895) [spigot-1.14.1.jar:git-Spigot-8043ebc-f690957]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:888) [spigot-1.14.1.jar:git-Spigot-8043ebc-f690957]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(SourceFile:99) [spigot-1.14.1.jar:git-Spigot-8043ebc-f690957]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:871) [spigot-1.14.1.jar:git-Spigot-8043ebc-f690957]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:805) [spigot-1.14.1.jar:git-Spigot-8043ebc-f690957]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.NoSuchMethodError: org.bukkit.inventory.Inventory.getName()Ljava/lang/String;
	at com.gmail.zariust.otherdrops.subject.BlockTarget.<init>(BlockTarget.java:78) ~[?:?]
	at com.gmail.zariust.otherdrops.event.OccurredEvent.<init>(OccurredEvent.java:119) ~[?:?]
	at com.gmail.zariust.otherdrops.listener.OdBlockListener.onBlockBreak(OdBlockListener.java:104) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor206.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-f690957]
	... 19 more
```

**Comment by CoolLord22** [comment]
Patched by changes in master branch
