### ISSUE TITLE
Async Entity Add

### ISSUE THREAD

**Issue by jasuogra** [CoolLord22/OtherDrops#71]
**Describe the bug**
After kill pig i get stacktrace, issue happens with WildStacker, only in world which is specified in config to drop:

  pig:
    - drop: NOTHING
    - drop: COOKED_PORK
      world: EMPTYWORLD
      quantity: 1-1
      chance: 100%

00:35:23 ERROR]: Could not pass event AsyncEntityDeathEvent to OtherDrops v3.2.7
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[mc1.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[mc1.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[mc1.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:482) ~[mc1.jar:git-Spigot-dcd1643-e60fc34]
        at com.bgsoftware.wildstacker.listeners.EntitiesListener.lambda$onEntityLastDamage$2(EntitiesListener.java:128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.IllegalStateException: Asynchronous entity add!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[mc1.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.World.addEntity(World.java:1017) ~[mc1.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.WorldServer.addEntity(WorldServer.java:1115) ~[mc1.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.dropItem(CraftWorld.java:295) ~[mc1.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.dropItemNaturally(CraftWorld.java:334) ~[mc1.jar:git-Spigot-dcd1643-e60fc34]
        at com.gmail.zariust.otherdrops.drop.DropType.drop(DropType.java:223) ~[?:?]
        at com.gmail.zariust.otherdrops.drop.ItemDrop.performDrop(ItemDrop.java:158) ~[?:?]
        at com.gmail.zariust.otherdrops.drop.DropType.dropLocal(DropType.java:173) ~[?:?]
        at com.gmail.zariust.otherdrops.drop.DropType.drop(DropType.java:150) ~[?:?]
        at com.gmail.zariust.otherdrops.event.DropRunner.performDrop(DropRunner.java:267) ~[?:?]
        at com.gmail.zariust.otherdrops.event.DropRunner.run(DropRunner.java:106) ~[?:?]
        at com.gmail.zariust.otherdrops.SectionManager.scheduleDrop(SectionManager.java:423) ~[?:?]
        at com.gmail.zariust.otherdrops.SectionManager.performDrop(SectionManager.java:153) ~[?:?]
        at com.gmail.zariust.otherdrops.listener.OdEntityListener.onEntityDeath(OdEntityListener.java:86) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor282.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[mc1.jar:git-Spigot-dcd1643-e60fc34]
        ... 7 more
>

**To Reproduce**
1. Kill pig in world specified to drop
2. Check console

**Desktop (please complete the following information):**
 - Java Version 1.8.0_191
 - Server VersionThis server is running CraftBukkit version git-Spigot-dcd1643-e60fc34 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
 - Plugin Version 3.2.7

**Comment by CoolLord22** [comment]
Issue doesn't seem to really be *caused* by OtherDrops as I can't duplicate it on my server with just OD loaded. If anyone else has this issue please update and reopen this ticket so we can check it out again :)
