### ISSUE TITLE
Error console OtherDrops 3.2.6

### ISSUE THREAD

**Issue by MrKatrioPL** [CoolLord22/OtherDrops#84]
- OS: Linux
 - Java Version:
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~16.04.1-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)
 - Server Version: Paper 1.14.4
 - Plugin Version 3.2.6

```
[18:58:16] [Server thread/ERROR]: Error occurred while enabling OtherDrops v3.2.6 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.Bukkit.getServerId()Ljava/lang/String;
	at com.gmail.zariust.otherdrops.OtherDrops.exportServerDetails(OtherDrops.java:173) ~[?:?]
	at com.gmail.zariust.otherdrops.OtherDrops.exportEnumLists(OtherDrops.java:160) ~[?:?]
	at com.gmail.zariust.otherdrops.OtherDrops.onEnable(OtherDrops.java:91) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[paper.jar:git-Paper-163]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[paper.jar:git-Paper-163]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[paper.jar:git-Paper-163]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[paper.jar:git-Paper-163]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[paper.jar:git-Paper-163]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.reload(CraftServer.java:859) ~[paper.jar:git-Paper-163]
	at org.bukkit.Bukkit.reload(Bukkit.java:610) ~[paper.jar:git-Paper-163]
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54) ~[paper.jar:git-Paper-163]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper.jar:git-Paper-163]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739) ~[paper.jar:git-Paper-163]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchServerCommand(CraftServer.java:701) ~[paper.jar:git-Paper-163]
	at net.minecraft.server.v1_14_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:456) ~[paper.jar:git-Paper-163]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[paper.jar:git-Paper-163]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1074) ~[paper.jar:git-Paper-163]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:918) ~[paper.jar:git-Paper-163]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
```
```
[18:58:22] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'otherdrops' in plugin OtherDrops v3.2.6 - plugin is disabled.
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[paper.jar:git-Paper-163]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper.jar:git-Paper-163]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739) ~[paper.jar:git-Paper-163]
	at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1800) ~[paper.jar:git-Paper-163]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1608) ~[paper.jar:git-Paper-163]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[paper.jar:git-Paper-163]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[paper.jar:git-Paper-163]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[paper.jar:git-Paper-163]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[paper.jar:git-Paper-163]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[paper.jar:git-Paper-163]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[paper.jar:git-Paper-163]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[paper.jar:git-Paper-163]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1012) ~[paper.jar:git-Paper-163]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1005) ~[paper.jar:git-Paper-163]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[paper.jar:git-Paper-163]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:989) ~[paper.jar:git-Paper-163]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:922) ~[paper.jar:git-Paper-163]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
```

**Comment by CoolLord22** [comment]
Even though the error hasn't been reported, the issue is because you're using 3.2.6 on 1.14.4 server. The version you'll need for 1.14 is 3.2.7 Beta which is available through #plugin-selection channel on Discord.
