### ISSUE TITLE
OtherDrops does not work on version 1.14.4 :(

### ISSUE THREAD

**Issue by MatteonX** [CoolLord22/OtherDrops#94]
Hello, I have a problem with OtherDrops on version 1.14.4 when I start the server there is a problem here:
[22:16:26 WARN]: Plugin OtherDrops v3.2.6 does not specify an api-version.
[22:16:27 ERROR]: Could not load 'plugins/OtherDrops1.13-3.2.6.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.IllegalArgumentException: Plugin already initialized!
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:138) ~[patched_1.14.4.jar:git-Paper-236]
at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:337) ~[patched_1.14.4.jar:git-Paper-236]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:257) ~[patched_1.14.4.jar:git-Paper-236]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.java:355) ~[patched_1.14.4.jar:git-Paper-236]
at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:226) ~[patched_1.14.4.jar:git-Paper-236]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:876) ~[patched_1.14.4.jar:git-Paper-236]
at java.lang.Thread.run(Thread.java:830) [?:?]
Caused by: java.lang.IllegalArgumentException: Plugin already initialized!
at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:171) ~[patched_1.14.4.jar:git-Paper-236]
at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:52) ~[patched_1.14.4.jar:git-Paper-236]
at com.gmail.zariust.otherdrops.OtherDrops.<init>(OtherDrops.java:79) ~[?:?]
at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?]
at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:166) ~[?:?]
at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:404) ~[?:?]
at java.lang.Class.newInstance(Class.java:591) ~[?:?]
at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:75) ~[patched_1.14.4.jar:git-Paper-236]
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:134) ~[patched_1.14.4.jar:git-Paper-236]
Caused by: java.lang.IllegalStateException: Initial initialization
at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:174) ~[patched_1.14.4.jar:git-Paper-236]

I tested the plugin on Java 7,8,9,10,11,12,13 server I have set up on Enderchest.pl I use windows 10 the current version of java on the server is 13 version of the plugin is 3.2.6 server version 1.14.4
other plugins work flawlessly

I'm sorry if I wrote something wrong, I'm from Poland and I only know the basics :)

**Comment by CoolLord22** [comment]
Currently the only version supporting 1.14 and above is OtherDrops 3.2.7 beta, you can install it from the Discord server (instructions found in FAQ of Wiki page)
